# Generated by Django 4.1 on 2023-06-15 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='name_of_file',
        ),
    ]
