# Generated by Django 4.1 on 2023-06-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0002_remove_datafile_name_of_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='total_downloads',
            field=models.IntegerField(default=0),
        ),
    ]
